[package]
name = "flymouse-input"
version = "0.1.0"
edition = "2021"

[dependencies]
flymouse-protocol = { workspace = true }
rdev = "0.5"
enigo = "0.2"
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
