[package]
name = "flymouse-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
tokio-util = { workspace = true }
anyhow = { workspace = true }
